services:
  yolo:
    build: 
        context: .
        dockerfile: Dockerfile
        args:
          CUDA_VERSION: ${CUDA_VERSION} 
    ports:
      - "8000:8000" 
    volumes:
      - /logs:/app/logs  
    network_mode: "host"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia

