[Server]
host = "0.0.0.0"
port = 8000
debug = false
is_active = true
object_detection = true
use_cuda = true

[API]
chosen_api = "Fast"

[Static]
static_directory = "app/static"

[Templates]
temp_directory= "app/templates"


[Logging]
log_file = "logs/app.log"
log_format = "<green>{time:MMM D, YYYY - HH:mm:ss}</green> || <level>{level}</level> || <cyan>{message}</cyan> || <red>{file.name}</red> ||"
rotation = "10 MB"



