[Server]
host = "0.0.0.0"
port = 8000
debug = true
is_active = true

[API]
chosen_api = "Fast"

[Static]
static_directory = "app/static"

[Templates]
temp_directory= "app/templates"

[Certificates]
cert_directory = "/home/dogan/cert.pem"
key_directory = "/home/dogan/key.pem"

[Logging]
log_file = "logs/app.log"
log_format = "<green>{time:MMM D, YYYY - HH:mm:ss}</green> || <level>{level}</level> || <cyan>{message}</cyan> || <red>{file.name}</red> ||"
rotation = "10 MB"

